name: deploy
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  workflow_dispatch:

jobs:
      Drain:
        runs-on: ubuntu-latest
        environment: Development_1
        steps:
          - run: echo "ðŸŽ‰ Drain job was called"

      Deploy:
        needs: Drain
        runs-on: ubuntu-latest
        environment: Development_2
        steps:
          - run: echo "ðŸŽ‰ Deploy job was called"


      Restore:
        needs: Deploy
        runs-on: ubuntu-latest
        environment: Development_2
        steps:
          - run: echo "ðŸŽ‰ Restore job was called"

